/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-22-2014
 * 
 * XDoclet definition:
 * @struts.form name="workStationForm"
 */
public class WorkStationForm extends ValidatorActionForm {
	/*
	 * Generated fields
	 */

	/** extension property */
	private String extension;

	/** id property */
	private String id;

	/** floorId property */
	private String floorId;

	/** description property */
	private String description;

	/** empId property */
	private String empId;

	/** type property */
	private String type;

	/** zoneId property */
	private String zoneId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Returns the extension.
	 * @return String
	 */
	public String getExtension() {
		return extension;
	}

	/** 
	 * Set the extension.
	 * @param extension The extension to set
	 */
	public void setExtension(String extension) {
		this.extension = extension;
	}

	/** 
	 * Returns the id.
	 * @return String
	 */
	public String getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/** 
	 * Returns the floorId.
	 * @return String
	 */
	public String getFloorId() {
		return floorId;
	}

	/** 
	 * Set the floorId.
	 * @param floorId The floorId to set
	 */
	public void setFloorId(String floorId) {
		this.floorId = floorId;
	}

	/** 
	 * Returns the description.
	 * @return String
	 */
	public String getDescription() {
		return description;
	}

	/** 
	 * Set the description.
	 * @param description The description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Returns the empId.
	 * @return String
	 */
	public String getEmpId() {
		return empId;
	}

	/** 
	 * Set the empId.
	 * @param empId The empId to set
	 */
	public void setEmpId(String empId) {
		this.empId = empId;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the zoneId.
	 * @return String
	 */
	public String getZoneId() {
		return zoneId;
	}

	/** 
	 * Set the zoneId.
	 * @param zoneId The zoneId to set
	 */
	public void setZoneId(String zoneId) {
		this.zoneId = zoneId;
	}
}