/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-20-2014
 * 
 * XDoclet definition:
 * @struts.form name="zoneForm"
 */
public class ZoneForm extends ValidatorActionForm {
	/*
	 * Generated fields
	 */

	/** floorId property */
	private String floorId;

	/** zoneDesc property */
	private String zoneDesc;

	/** zoneName property */
	private String zoneName;

	/** zoneId property */
	private String zoneId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the floorId.
	 * @return String
	 */
	public String getFloorId() {
		return floorId;
	}

	/** 
	 * Set the floorId.
	 * @param floorId The floorId to set
	 */
	public void setFloorId(String floorId) {
		this.floorId = floorId;
	}

	/** 
	 * Returns the zoneDesc.
	 * @return String
	 */
	public String getZoneDesc() {
		return zoneDesc;
	}

	/** 
	 * Set the zoneDesc.
	 * @param zoneDesc The zoneDesc to set
	 */
	public void setZoneDesc(String zoneDesc) {
		this.zoneDesc = zoneDesc;
	}

	/** 
	 * Returns the zoneName.
	 * @return String
	 */
	public String getZoneName() {
		return zoneName;
	}

	/** 
	 * Set the zoneName.
	 * @param zoneName The zoneName to set
	 */
	public void setZoneName(String zoneName) {
		this.zoneName = zoneName;
	}

	/** 
	 * Returns the zoneId.
	 * @return String
	 */
	public String getZoneId() {
		return zoneId;
	}

	/** 
	 * Set the zoneId.
	 * @param zoneId The zoneId to set
	 */
	public void setZoneId(String zoneId) {
		this.zoneId = zoneId;
	}
}