/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-13-2014
 * 
 * XDoclet definition:
 * @struts.form name="workStationForm"
 */
public class WorkStationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** extension property */
	private String extension;

	/** floorId property */
	private String floorId;

	/** description property */
	private String description;

	/** workStationId property */
	private String workStationId;

	/** type property */
	private String type;

	/** zoneId property */
	private String zoneId;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the extension.
	 * @return String
	 */
	public String getExtension() {
		return extension;
	}

	/** 
	 * Set the extension.
	 * @param extension The extension to set
	 */
	public void setExtension(String extension) {
		this.extension = extension;
	}

	/** 
	 * Returns the floorId.
	 * @return String
	 */
	public String getFloorId() {
		return floorId;
	}

	/** 
	 * Set the floorId.
	 * @param floorId The floorId to set
	 */
	public void setFloorId(String floorId) {
		this.floorId = floorId;
	}

	/** 
	 * Returns the description.
	 * @return String
	 */
	public String getDescription() {
		return description;
	}

	/** 
	 * Set the description.
	 * @param description The description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/** 
	 * Returns the workStationId.
	 * @return String
	 */
	public String getWorkStationId() {
		return workStationId;
	}

	/** 
	 * Set the workStationId.
	 * @param workStationId The workStationId to set
	 */
	public void setWorkStationId(String workStationId) {
		this.workStationId = workStationId;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(String type) {
		this.type = type;
	}

	/** 
	 * Returns the zoneId.
	 * @return String
	 */
	public String getZoneId() {
		return zoneId;
	}

	/** 
	 * Set the zoneId.
	 * @param zoneId The zoneId to set
	 */
	public void setZoneId(String zoneId) {
		this.zoneId = zoneId;
	}
}