/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vcs.hibernate.Floor;
import com.vcs.service.ServiceFactory;
import com.vcs.service.ZoneService;


public class ZonePreAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		ZoneService zoneService=ServiceFactory.getZoneService();
		Floor floor=new Floor();
		List floorList=null;
		floorList=zoneService.floorData(floor);
		
		HttpSession httpSession=request.getSession();
		httpSession.setAttribute("floorList",floorList);
		
		return mapping.findForward("success");
	}
}