/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sun.org.apache.commons.beanutils.BeanUtils;
import com.vcs.hibernate.Floor;
import com.vcs.service.FloorService;
import com.vcs.service.ServiceFactory;
import com.vcs.struts.constants.WSContants;
import com.vcs.struts.form.FloorForm;

public class FloorSearchAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FloorForm floorForm = (FloorForm) form;
		
		FloorService floorService=ServiceFactory.getFloorService();
		System.out.println("floorId:" + floorForm.getFloorId());

		List<Floor> floorList = new ArrayList<Floor>();
		Floor floor = new Floor();
		try {
			BeanUtils.copyProperties(floor, floorForm);
		} catch (IllegalAccessException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (InvocationTargetException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		String status = "";
		String id = request.getParameter("floorId");
		int floorId = 0;
		int noOfRecords = 0;
		int pageNum = 1;
		int recordsPerPage = WSContants.RECORDS_PER_PAGE;

		if (id != null && !"".equals(id)) {
			floorId = Integer.parseInt(id);
		}

		if (request.getParameter("page") != null) {
			pageNum = Integer.parseInt(request.getParameter("page"));
		}

		int startRow = (recordsPerPage * pageNum - (recordsPerPage)) + 1;
		int endRow = (recordsPerPage * pageNum);
		int noOfPages = (int) Math.ceil(noOfRecords * 1.0 / recordsPerPage);

			floorList =floorService.search(floorId, startRow, endRow);
			noOfRecords =floorService.getCount(floorId);

		HttpSession hsession=request.getSession();
		if (floorList.size() > 0) {
			hsession.setAttribute("floorList", floorList);
			hsession.setAttribute("noOfPages", noOfPages);
			hsession.setAttribute("currentPage", pageNum);
			hsession.setAttribute("noOfRecords", noOfRecords);
			
		} else {
			hsession.setAttribute("status", status);
		}
		return mapping.findForward("success");
	}
}