/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sun.org.apache.commons.beanutils.BeanUtils;
import com.vcs.hibernate.Zone;
import com.vcs.struts.constants.WSContants;
import com.vcs.struts.dao.ZoneDao;
import com.vcs.struts.form.ZoneForm;

public class ZoneSearchAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ZoneForm zoneForm = (ZoneForm) form;
		System.out.println("zoneId:" + zoneForm.getZoneId());

		ZoneDao zoneDao = new ZoneDao();
		List zoneList = new ArrayList();
		Zone zone = new Zone();
		try {
			BeanUtils.copyProperties(zone, zoneForm);
		} catch (IllegalAccessException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} catch (InvocationTargetException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}

		String status = "";
		String id = request.getParameter("zoneId");
		int zoneId = 0;
		int noOfRecords = 0;
		int pageNum = 1;
		int recordsPerPage = WSContants.RECORDS_PER_PAGE;

		if (id != null && !"".equals(id)) {
			zoneId = Integer.parseInt(id);
		}

		if (request.getParameter("page") != null) {
			pageNum = Integer.parseInt(request.getParameter("page"));
		}

		int startRow = (recordsPerPage * pageNum - (recordsPerPage)) + 1;
		int endRow = (recordsPerPage * pageNum);

		ZoneDao zoneSearch = new ZoneDao();

		try {
			zoneList = zoneSearch.search(zoneId, startRow, endRow);
			noOfRecords = zoneSearch.getCount(zoneId);
			status="Records are not fount given criteria";
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		int noOfPages = (int) Math.ceil(noOfRecords * 1.0 / recordsPerPage);

		HttpSession hsession = request.getSession();

		if (zoneList.size() > 0) {
			hsession.setAttribute("zoneList", zoneList);
			hsession.setAttribute("noOfPages", noOfPages);
			hsession.setAttribute("currentPage", pageNum);
			hsession.setAttribute("noOfRecords", noOfRecords);

		} else {
			hsession.setAttribute("status", status);
		}
		return mapping.findForward("success");
	}
}